'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Bell, BriefcaseBusiness, CalendarDays, Check, ChevronRight, CircleDollarSign, HeartHandshake, Instagram, Megaphone, MessageCircle, Plus, Search, Send, Sparkles, Target, Trash2, Users, WalletCards, X } from 'lucide-react'

type Tab = 'Home' | 'Discover' | 'Services' | 'Campaigns' | 'Messages' | 'Planner' | 'Payments' | 'Profile'
type Role = 'Creator' | 'Advertiser' | 'Both'
type Service = { id:string; owner:string; title:string; category:string; price:number; unit:string; platform:string; description:string }
type Campaign = { id:string; title:string; owner:string; budget:string; category:string; platform:string; status:'Open'|'Draft'|'Active'|'Completed'; deadline:string; brief:string; applicants:number }
type Message = { id:string; from:string; to:string; text:string; time:string; unread:boolean }
type PaymentMethod = { id:string; label:string; type:'Meta Pay'|'Instagram'|'Facebook'|'External link'; handle:string; enabled:boolean }
type Creator = { id:string; name:string; handle:string; category:string; followers:string; engagement:string; platform:string; bio:string; verified:boolean }
type Contact = { name:string }

const creators:Creator[] = [
 {id:'u1',name:'Maya Chen',handle:'@mayamakes',category:'Beauty & Lifestyle',followers:'182K',engagement:'6.8%',platform:'Instagram',bio:'Beauty, everyday routines and thoughtful product storytelling.',verified:true},
 {id:'u2',name:'Jordan Ellis',handle:'@jordaneats',category:'Food',followers:'96K',engagement:'8.2%',platform:'TikTok',bio:'Food discoveries, local spots and simple recipe content.',verified:true},
 {id:'u3',name:'Noah Rivera',handle:'@noahbuilds',category:'Technology',followers:'241K',engagement:'4.9%',platform:'YouTube',bio:'Practical technology, software and creator tools.',verified:false},
 {id:'u4',name:'Ava Morgan',handle:'@avamoves',category:'Wellness',followers:'74K',engagement:'7.4%',platform:'Instagram',bio:'Movement, healthy routines and approachable wellness.',verified:true},
 {id:'u5',name:'Lena Brooks',handle:'@lenabrooks',category:'Travel',followers:'128K',engagement:'5.9%',platform:'Instagram',bio:'Slow travel, destinations and useful trip planning.',verified:false},
 {id:'u6',name:'Eli Park',handle:'@eliparktech',category:'Technology',followers:'89K',engagement:'7.1%',platform:'TikTok',bio:'Short-form tech explainers and product discoveries.',verified:false},
]
const starterServices:Service[] = [
 {id:'s1',owner:'Maya Chen',title:'Instagram product feature',category:'Sponsored content',price:450,unit:'per post',platform:'Instagram',description:'One polished feed post with product integration and caption.'},
 {id:'s2',owner:'Jordan Ellis',title:'Recipe integration',category:'Sponsored content',price:600,unit:'per video',platform:'TikTok',description:'Short recipe video with natural brand integration.'},
 {id:'s3',owner:'Noah Rivera',title:'YouTube product review',category:'Video',price:1200,unit:'per video',platform:'YouTube',description:'Dedicated or integrated technology review with clear disclosure.'},
 {id:'s4',owner:'Ava Morgan',title:'Wellness campaign package',category:'Campaign package',price:900,unit:'package',platform:'Instagram',description:'Two posts and three stories around one campaign theme.'},
]
const starterCampaigns:Campaign[] = [
 {id:'c1',title:'Fall creator partnerships',owner:'Northstar Studio',budget:'$2,000–$5,000',category:'Lifestyle',platform:'Instagram',status:'Open',deadline:'Oct 10, 2026',brief:'Looking for lifestyle creators to introduce a new seasonal product.',applicants:12},
 {id:'c2',title:'Independent tech voices',owner:'Bright Devices',budget:'$3,000–$8,000',category:'Technology',platform:'YouTube',status:'Open',deadline:'Oct 18, 2026',brief:'Creators wanted for practical, honest technology content.',applicants:8},
 {id:'c3',title:'Weekend wellness stories',owner:'Northstar Studio',budget:'$1,000–$3,000',category:'Wellness',platform:'Instagram',status:'Active',deadline:'Sep 28, 2026',brief:'A small creator group for an approachable wellness campaign.',applicants:18},
]
const starterMessages:Message[] = [
 {id:'m1',from:'Maya Chen',to:'Northstar Studio',text:'Thanks! I would love to discuss the fall campaign brief.',time:'9:42 PM',unread:true},
 {id:'m2',from:'You',to:'Noah Rivera',text:'Your YouTube package looks like a strong fit for our launch.',time:'8:16 PM',unread:false},
 {id:'m3',from:'Jordan Ellis',to:'You',text:'I can deliver the recipe integration next week.',time:'Yesterday',unread:false},
]
const starterPayments:PaymentMethod[] = [
 {id:'pm1',label:'Instagram / Meta Pay',type:'Instagram',handle:'@mayamakes',enabled:true},
 {id:'pm2',label:'Facebook / Meta Pay',type:'Facebook',handle:'Northstar Studio',enabled:true},
]
function money(n:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
function uid(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}

export default function HomePage(){
 const [tab,setTab]=useState<Tab>('Home'),[role,setRole]=useState<Role>('Both'),[search,setSearch]=useState('')
 const [services,setServices]=useState(starterServices),[campaigns,setCampaigns]=useState(starterCampaigns),[messages,setMessages]=useState(starterMessages),[paymentMethods,setPaymentMethods]=useState(starterPayments),[saved,setSaved]=useState<string[]>([])
 const [toast,setToast]=useState(''),[modal,setModal]=useState<'service'|'campaign'|'payment'|'message'|null>(null),[selected,setSelected]=useState<Contact|null>(null),[messageText,setMessageText]=useState('')
 const [serviceForm,setServiceForm]=useState({title:'',category:'Sponsored content',price:'',unit:'per post',platform:'Instagram',description:''})
 const [campaignForm,setCampaignForm]=useState({title:'',budget:'',category:'Lifestyle',platform:'Instagram',deadline:'',brief:''})
 const [paymentForm,setPaymentForm]=useState({label:'',type:'Instagram',handle:''})
 useEffect(()=>{try{const raw=localStorage.getItem('shineu-marketplace');if(!raw)return;const s=JSON.parse(raw);if(s.services)setServices(s.services);if(s.campaigns)setCampaigns(s.campaigns);if(s.messages)setMessages(s.messages);if(s.paymentMethods)setPaymentMethods(s.paymentMethods);if(s.saved)setSaved(s.saved)}catch{}},[])
 useEffect(()=>{try{localStorage.setItem('shineu-marketplace',JSON.stringify({services,campaigns,messages,paymentMethods,saved}))}catch{}},[services,campaigns,messages,paymentMethods,saved])
 const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),2600)}
 const filteredCreators=useMemo(()=>creators.filter(x=>`${x.name} ${x.handle} ${x.category} ${x.platform}`.toLowerCase().includes(search.toLowerCase())),[search])
 const filteredServices=useMemo(()=>services.filter(x=>`${x.owner} ${x.title} ${x.category} ${x.platform}`.toLowerCase().includes(search.toLowerCase())),[services,search])
 const filteredCampaigns=useMemo(()=>campaigns.filter(x=>`${x.title} ${x.owner} ${x.category} ${x.platform}`.toLowerCase().includes(search.toLowerCase())),[campaigns,search])
 const toggleSave=(id:string)=>setSaved(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])
 const openMessage=(person:string)=>{setSelected({name:person});setMessageText('');setModal('message')}
 const sendMessage=()=>{if(!messageText.trim()||!selected)return;setMessages(x=>[{id:uid('m'),from:'You',to:selected.name,text:messageText.trim(),time:'Just now',unread:false},...x]);setMessageText('');setModal(null);notify(`Message sent to ${selected.name}`)}
 const createService=()=>{if(!serviceForm.title.trim())return notify('Add a service title');const item:Service={id:uid('s'),owner:'You',title:serviceForm.title.trim(),category:serviceForm.category,price:Number(serviceForm.price)||0,unit:serviceForm.unit,platform:serviceForm.platform,description:serviceForm.description||'Creator service available for collaboration.'};setServices(x=>[item,...x]);setServiceForm({title:'',category:'Sponsored content',price:'',unit:'per post',platform:'Instagram',description:''});setModal(null);notify('Service published')}
 const createCampaign=()=>{if(!campaignForm.title.trim())return notify('Add a campaign title');const item:Campaign={id:uid('c'),title:campaignForm.title.trim(),owner:'You',budget:campaignForm.budget||'Open budget',category:campaignForm.category,platform:campaignForm.platform,status:'Open',deadline:campaignForm.deadline||'Flexible',brief:campaignForm.brief||'Campaign details available after contact.',applicants:0};setCampaigns(x=>[item,...x]);setCampaignForm({title:'',budget:'',category:'Lifestyle',platform:'Instagram',deadline:'',brief:''});setModal(null);notify('Free campaign published')}
 const addPayment=()=>{if(!paymentForm.handle.trim())return notify('Add your Meta or payment handle');const item:PaymentMethod={id:uid('pm'),label:paymentForm.label||`${paymentForm.type} payment`,type:paymentForm.type as PaymentMethod['type'],handle:paymentForm.handle.trim(),enabled:true};setPaymentMethods(x=>[item,...x]);setPaymentForm({label:'',type:'Instagram',handle:''});setModal(null);notify('Payment method added')}
 useEffect(()=>{const close=()=>setModal(null);window.addEventListener('shineu-close-modal',close);return()=>window.removeEventListener('shineu-close-modal',close)},[])
 return <div className="shineu-shell">
  <header className="main-header"><button className="logo" onClick={()=>setTab('Home')}><span>S</span><strong>ShineU</strong></button><nav className="main-nav">{(['Home','Discover','Services','Campaigns','Messages','Planner','Payments'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}{x==='Messages'&&messages.some(m=>m.unread)&&<i/>}</button>)}</nav><div className="header-right"><label className="header-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search creators, services…"/></label><button className="round-btn" onClick={()=>notify('You have 1 new collaboration update')}><Bell size={17}/></button><button className="profile-chip" onClick={()=>setTab('Profile')}><span>GE</span><b>Gio</b></button></div></header>
  <main className="main-wrap">
   {tab==='Home'&&<HomeView setTab={setTab} role={role} setRole={setRole} campaigns={campaigns} services={services} creators={creators} saved={saved} toggleSave={toggleSave} openMessage={openMessage} setModal={setModal}/>} 
   {tab==='Discover'&&<DiscoverView creators={filteredCreators} saved={saved} toggleSave={toggleSave} openMessage={openMessage}/>} 
   {tab==='Services'&&<ServicesView services={filteredServices} saved={saved} toggleSave={toggleSave} openMessage={openMessage} setModal={setModal}/>} 
   {tab==='Campaigns'&&<CampaignsView campaigns={filteredCampaigns} setModal={setModal} openMessage={openMessage}/>} 
   {tab==='Messages'&&<MessagesView messages={messages} openMessage={openMessage}/>} 
   {tab==='Planner'&&<PlannerView campaigns={campaigns} services={services}/>} 
   {tab==='Payments'&&<PaymentsView methods={paymentMethods} setMethods={setPaymentMethods} setModal={setModal}/>} 
   {tab==='Profile'&&<ProfileView role={role} setRole={setRole} paymentMethods={paymentMethods} setModal={setModal} notify={notify}/>} 
  </main>
  <footer className="footer"><div><b>ShineU</b><span>Free planning and collaboration workspace for creators and advertisers.</span></div><span>Payments are arranged directly between collaborators.</span></footer>
  {modal==='service'&&<Modal title="Publish a service" subtitle="Let advertisers discover what you offer."><Field label="Service title"><input autoFocus value={serviceForm.title} onChange={e=>setServiceForm({...serviceForm,title:e.target.value})} placeholder="Instagram product feature"/></Field><div className="form-grid"><Field label="Category"><select value={serviceForm.category} onChange={e=>setServiceForm({...serviceForm,category:e.target.value})}><option>Sponsored content</option><option>Video</option><option>UGC</option><option>Campaign package</option><option>Affiliate promotion</option><option>Event coverage</option></select></Field><Field label="Platform"><select value={serviceForm.platform} onChange={e=>setServiceForm({...serviceForm,platform:e.target.value})}><option>Instagram</option><option>Facebook</option><option>TikTok</option><option>YouTube</option><option>LinkedIn</option></select></Field></div><div className="form-grid"><Field label="Price"><input type="number" value={serviceForm.price} onChange={e=>setServiceForm({...serviceForm,price:e.target.value})} placeholder="500"/></Field><Field label="Unit"><select value={serviceForm.unit} onChange={e=>setServiceForm({...serviceForm,unit:e.target.value})}><option>per post</option><option>per video</option><option>per story</option><option>package</option><option>per campaign</option></select></Field></div><Field label="Description"><textarea value={serviceForm.description} onChange={e=>setServiceForm({...serviceForm,description:e.target.value})} placeholder="Explain what the advertiser receives…"/></Field><ModalActions close={()=>setModal(null)} action={createService} label="Publish service"/></Modal>}
  {modal==='campaign'&&<Modal title="Create a free campaign" subtitle="Post an opportunity and let relevant creators contact you."><Field label="Campaign title"><input autoFocus value={campaignForm.title} onChange={e=>setCampaignForm({...campaignForm,title:e.target.value})} placeholder="Fall creator partnerships"/></Field><div className="form-grid"><Field label="Budget"><input value={campaignForm.budget} onChange={e=>setCampaignForm({...campaignForm,budget:e.target.value})} placeholder="$2,000–$5,000"/></Field><Field label="Platform"><select value={campaignForm.platform} onChange={e=>setCampaignForm({...campaignForm,platform:e.target.value})}><option>Instagram</option><option>Facebook</option><option>TikTok</option><option>YouTube</option><option>Multi-platform</option></select></Field></div><div className="form-grid"><Field label="Category"><select value={campaignForm.category} onChange={e=>setCampaignForm({...campaignForm,category:e.target.value})}><option>Lifestyle</option><option>Beauty</option><option>Technology</option><option>Food</option><option>Travel</option><option>Wellness</option><option>Fashion</option></select></Field><Field label="Deadline"><input type="date" value={campaignForm.deadline} onChange={e=>setCampaignForm({...campaignForm,deadline:e.target.value})}/></Field></div><Field label="Brief"><textarea value={campaignForm.brief} onChange={e=>setCampaignForm({...campaignForm,brief:e.target.value})} placeholder="What are you promoting and what kind of creator are you looking for?"/></Field><ModalActions close={()=>setModal(null)} action={createCampaign} label="Publish campaign"/></Modal>}
  {modal==='payment'&&<Modal title="Add payment method" subtitle="ShineU does not hold money. Add the payment route you use to settle collaborations directly."><div className="notice"><CircleDollarSign size={17}/><span>Use a payment profile or payment link you control. Never share passwords, card numbers or security codes here.</span></div><Field label="Label"><input autoFocus value={paymentForm.label} onChange={e=>setPaymentForm({...paymentForm,label:e.target.value})} placeholder="Instagram / Meta Pay"/></Field><Field label="Payment route"><select value={paymentForm.type} onChange={e=>setPaymentForm({...paymentForm,type:e.target.value as PaymentMethod['type']})}><option>Instagram</option><option>Facebook</option><option>Meta Pay</option><option>External link</option></select></Field><Field label="Handle or payment link"><input value={paymentForm.handle} onChange={e=>setPaymentForm({...paymentForm,handle:e.target.value})} placeholder="Your public payment handle or link"/></Field><ModalActions close={()=>setModal(null)} action={addPayment} label="Save payment method"/></Modal>}
  {modal==='message'&&selected&&<Modal title={`Contact ${selected.name}`} subtitle="Start the collaboration conversation in ShineU."><div className="contact-mini"><div className="avatar">{selected.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{selected.name}</b><span>Keep campaign details, deliverables and expectations clear.</span></div></div><Field label="Message"><textarea autoFocus value={messageText} onChange={e=>setMessageText(e.target.value)} placeholder="Hi! I found your profile through ShineU…"/></Field><ModalActions close={()=>setModal(null)} action={sendMessage} label="Send message"/></Modal>}
  {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}

function HomeView({setTab,role,setRole,campaigns,services,creators,saved,toggleSave,openMessage,setModal}:{setTab:(x:Tab)=>void;role:Role;setRole:(x:Role)=>void;campaigns:Campaign[];services:Service[];creators:Creator[];saved:string[];toggleSave:(x:string)=>void;openMessage:(x:string)=>void;setModal:(x:'service'|'campaign'|'payment'|'message'|null)=>void}){return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> Free creator collaboration workspace</div><h1>Find the right people.<br/><em>Plan the work.</em></h1><p>ShineU helps influencers and advertisers discover each other, publish services, create free campaigns, message directly and keep collaborations organized.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab('Discover')}>Explore creators <ArrowRight size={16}/></button><button className="secondary" onClick={()=>setModal('campaign')}>Create a campaign</button></div></div><div className="hero-card"><div className="hero-card-top"><span>Today on ShineU</span><span className="live"><i/> Live</span></div><div className="hero-stat"><strong>{creators.length + 124}</strong><span>creator profiles</span></div><div className="hero-stat"><strong>{services.length + 37}</strong><span>services listed</span></div><div className="hero-stat"><strong>{campaigns.length + 19}</strong><span>open opportunities</span></div><div className="mini-note"><HeartHandshake size={16}/><span>Collaboration starts with a conversation — no ShineU transaction fee.</span></div></div></section><section className="role-switch"><span>I’m here as</span>{(['Creator','Advertiser','Both'] as Role[]).map(x=><button key={x} className={role===x?'active':''} onClick={()=>setRole(x)}>{x}</button>)}</section><SectionHeader title="Recommended creators" action="See all" onClick={()=>setTab('Discover')}/><div className="creator-grid">{creators.slice(0,4).map(c=><CreatorCard key={c.id} creator={c} saved={saved.includes(c.id)} toggleSave={toggleSave} contact={openMessage}/>)}</div><SectionHeader title="Services you can book" action="Browse services" onClick={()=>setTab('Services')}/><div className="service-grid">{services.slice(0,3).map(s=><ServiceCard key={s.id} service={s} saved={saved.includes(s.id)} toggleSave={toggleSave} contact={openMessage}/>)}</div><SectionHeader title="Open campaigns" action="View campaigns" onClick={()=>setTab('Campaigns')}/><div className="campaign-list">{campaigns.filter(c=>c.status==='Open').slice(0,3).map(c=><CampaignRow key={c.id} campaign={c} contact={openMessage}/>)}</div></>}
function DiscoverView({creators,saved,toggleSave,openMessage}:{creators:Creator[];saved:string[];toggleSave:(x:string)=>void;openMessage:(x:string)=>void}){return <><PageTitle eyebrow="Discover" title="Find creators to work with" text="Search by niche, platform, audience and engagement. Contact creators directly when you find a fit."/><div className="filter-row"><button className="filter active">All creators</button><button className="filter">Instagram</button><button className="filter">TikTok</button><button className="filter">YouTube</button><button className="filter">High engagement</button></div><div className="creator-grid large-grid">{creators.map(c=><CreatorCard key={c.id} creator={c} saved={saved.includes(c.id)} toggleSave={toggleSave} contact={openMessage}/>)}</div>{creators.length===0&&<Empty text="No creators match your search."/>}</>}
function ServicesView({services,saved,toggleSave,openMessage,setModal}:{services:Service[];saved:string[];toggleSave:(x:string)=>void;openMessage:(x:string)=>void;setModal:(x:'service'|'campaign'|'payment'|'message'|null)=>void}){return <><PageTitle eyebrow="Marketplace" title="Creator services" text="Creators can publish clear offers. Advertisers can discover services and start a conversation without a marketplace fee." action={<button className="primary" onClick={()=>setModal('service')}><Plus size={16}/> Publish a service</button>}/><div className="service-grid large-grid">{services.map(s=><ServiceCard key={s.id} service={s} saved={saved.includes(s.id)} toggleSave={toggleSave} contact={openMessage}/>)}</div></>}
function CampaignsView({campaigns,setModal,openMessage}:{campaigns:Campaign[];setModal:(x:'service'|'campaign'|'payment'|'message'|null)=>void;openMessage:(x:string)=>void}){return <><PageTitle eyebrow="Opportunities" title="Free campaigns" text="Advertisers can post campaigns for free. Creators can review the brief and contact the advertiser to discuss a collaboration." action={<button className="primary" onClick={()=>setModal('campaign')}><Plus size={16}/> Create campaign</button>}/><div className="campaign-stack">{campaigns.map(c=><CampaignRow key={c.id} campaign={c} contact={openMessage} detailed/>)}</div></>}
function MessagesView({messages,openMessage}:{messages:Message[];openMessage:(x:string)=>void}){return <><PageTitle eyebrow="Inbox" title="Collaboration messages" text="Keep discovery, questions, campaign discussions and follow-ups in one place."/><div className="message-layout"><div className="message-list">{messages.map(m=><button key={m.id} className={m.unread?'message active':'message'} onClick={()=>openMessage(m.from==='You'?m.to:m.from)}><div className="avatar">{(m.from==='You'?m.to:m.from).split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{m.from==='You'?m.to:m.from}</b><p>{m.text}</p><small>{m.time}</small></div>{m.unread&&<i/>}</button>)}</div><div className="conversation"><MessageCircle size={28}/><h3>Choose a conversation</h3><p>Select a contact to continue a collaboration.</p></div></div></>}
function PlannerView({campaigns,services}:{campaigns:Campaign[];services:Service[]}){const open=campaigns.filter(c=>c.status!=='Completed');return <><PageTitle eyebrow="Planner" title="Your collaboration planner" text="A simple view of what is open, what is being discussed and what you can offer."/><div className="planner-grid"><PlannerColumn title="Opportunities" icon={<Target size={17}/>} items={open.map(c=>({title:c.title,meta:`${c.platform} · ${c.deadline}`,kind:'Campaign'}))}/><PlannerColumn title="Services" icon={<BriefcaseBusiness size={17}/>} items={services.filter(s=>s.owner==='You').map(s=>({title:s.title,meta:`${money(s.price)} ${s.unit}`,kind:'Service'}))}/><PlannerColumn title="Next steps" icon={<CalendarDays size={17}/>} items={[{title:'Review new creator messages',meta:'Today · Inbox',kind:'Message'},{title:'Confirm campaign deliverables',meta:'Tomorrow · Planner',kind:'Task'},{title:'Update payment details',meta:'This week · Payments',kind:'Task'}]}/></div></>}
function PaymentsView({methods,setMethods,setModal}:{methods:PaymentMethod[];setMethods:React.Dispatch<React.SetStateAction<PaymentMethod[]>>;setModal:(x:'service'|'campaign'|'payment'|'message'|null)=>void}){return <><PageTitle eyebrow="Payments" title="Your payment routes" text="ShineU is a planner and connection layer. You and your collaboration partner arrange payment directly through the method you choose." action={<button className="primary" onClick={()=>setModal('payment')}><Plus size={16}/> Add payment method</button>}/><div className="payment-info"><WalletCards size={21}/><div><b>Meta and social payment setup</b><p>You can list an Instagram or Facebook/Meta payment route so a collaborator knows how to settle a service. ShineU does not store card details or hold funds.</p></div></div><div className="payment-list">{methods.map(m=><div className="payment-row" key={m.id}><div className="payment-icon"><Instagram size={18}/></div><div><b>{m.label}</b><span>{m.type} · {m.handle}</span></div><span className="status">Enabled</span><button className="icon-btn" onClick={()=>setMethods(x=>x.filter(v=>v.id!==m.id))}><Trash2 size={15}/></button></div>)}</div></>}
function ProfileView({role,setRole,paymentMethods,setModal,notify}:{role:Role;setRole:(x:Role)=>void;paymentMethods:PaymentMethod[];setModal:(x:'service'|'campaign'|'payment'|'message'|null)=>void;notify:(x:string)=>void}){return <><PageTitle eyebrow="Profile" title="Your ShineU identity" text="Build a simple public profile so the right creators and advertisers know what you do."/><div className="profile-grid"><div className="profile-card"><div className="profile-cover"/><div className="profile-body"><div className="avatar xl">GE</div><h2>Gio Egre</h2><p className="handle">@shineu-member</p><p>Creator, advertiser or collaborator — describe your work, audience and the kinds of partnerships you want.</p><div className="role-pills">{(['Creator','Advertiser','Both'] as Role[]).map(x=><button className={role===x?'active':''} key={x} onClick={()=>setRole(x)}>{x}</button>)}</div><button className="secondary" onClick={()=>notify('Profile editing is ready for the next profile pass')}>Edit public profile</button></div></div><div className="profile-side"><div className="settings-card"><b>Payment methods</b><p>{paymentMethods.length} route{paymentMethods.length===1?'':'s'} available for collaboration.</p><button className="link-btn" onClick={()=>setModal('payment')}>Manage payments <ChevronRight size={14}/></button></div><div className="settings-card"><b>Privacy principle</b><p>Keep sensitive financial credentials outside ShineU. Only publish the public route another person needs to contact or pay you.</p></div></div></div></>}
function CreatorCard({creator,saved,toggleSave,contact}:{creator:Creator;saved:boolean;toggleSave:(x:string)=>void;contact:(x:string)=>void}){return <article className="card creator-card"><div className="card-top"><div className="avatar large">{creator.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><button className={saved?'save active':'save'} onClick={()=>toggleSave(creator.id)}>{saved?'Saved':'Save'}</button></div><h3>{creator.name}{creator.verified&&<span className="verified">✓</span>}</h3><p className="handle">{creator.handle} · {creator.platform}</p><span className="tag">{creator.category}</span><p className="bio">{creator.bio}</p><div className="stats"><span><b>{creator.followers}</b><small>followers</small></span><span><b>{creator.engagement}</b><small>engagement</small></span><span><b>Strong</b><small>fit</small></span></div><button className="outline full" onClick={()=>contact(creator.name)}><MessageCircle size={15}/> Contact</button></article>}
function ServiceCard({service,saved,toggleSave,contact}:{service:Service;saved:boolean;toggleSave:(x:string)=>void;contact:(x:string)=>void}){return <article className="card service-card"><div className="card-top"><span className="tag">{service.category}</span><button className={saved?'save active':'save'} onClick={()=>toggleSave(service.id)}>{saved?'Saved':'Save'}</button></div><h3>{service.title}</h3><p className="handle">{service.owner} · {service.platform}</p><p className="bio">{service.description}</p><div className="price"><strong>{money(service.price)}</strong><span>{service.unit}</span></div><button className="outline full" onClick={()=>contact(service.owner)}><Send size={15}/> Discuss service</button></article>}
function CampaignRow({campaign,contact,detailed=false}:{campaign:Campaign;contact:(x:string)=>void;detailed?:boolean}){return <article className={detailed?'campaign-row detailed':'campaign-row'}><div className="campaign-mark"><Megaphone size={18}/></div><div className="campaign-content"><div className="row-top"><span className="tag">{campaign.category}</span><span className={`status ${campaign.status.toLowerCase()}`}>{campaign.status}</span></div><h3>{campaign.title}</h3><p>{campaign.owner} · {campaign.platform} · {campaign.budget}</p>{detailed&&<div className="brief">{campaign.brief}</div>}<div className="campaign-meta"><span><CalendarDays size={13}/> {campaign.deadline}</span><span><Users size={13}/> {campaign.applicants} interested</span></div></div><button className="outline" onClick={()=>contact(campaign.owner)}>Contact</button></article>}
function PlannerColumn({title,icon,items}:{title:string;icon:React.ReactNode;items:{title:string;meta:string;kind:string}[]}){return <div className="planner-column"><div className="column-head">{icon}<b>{title}</b><span>{items.length}</span></div>{items.map((x,i)=><div className="planner-item" key={`${x.title}-${i}`}><div className="dot"/><div><b>{x.title}</b><small>{x.meta}</small></div><em>{x.kind}</em></div>)}</div>}
function PageTitle({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:React.ReactNode}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function SectionHeader({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="section-head"><h2>{title}</h2><button onClick={onClick}>{action} <ArrowRight size={14}/></button></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="round-btn" onClick={()=>window.dispatchEvent(new CustomEvent('shineu-close-modal'))}><X size={17}/></button></div>{children}</div></div>}
function ModalActions({close,action,label}:{close:()=>void;action:()=>void;label:string}){return <div className="modal-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={action}>{label} <ArrowRight size={15}/></button></div>}
function Empty({text}:{text:string}){return <div className="empty"><Search size={20}/><p>{text}</p></div>}
