'use client'

import { useMemo, useState } from 'react'
import { Activity, ArrowUpRight, Bell, CalendarDays, ChevronDown, CircleDollarSign, ClipboardCheck, Filter, Gauge, HeartHandshake, LayoutDashboard, Megaphone, MoreHorizontal, Plus, Search, Settings, Sparkles, Target, TrendingUp, Users, WalletCards, X } from 'lucide-react'

type Creator = { name:string; handle:string; category:string; followers:string; engagement:string; score:number; status:string; initials:string }
const creators: Creator[] = [
 {name:'Maya Chen',handle:'@mayamakes',category:'Beauty',followers:'182K',engagement:'6.8%',score:94,status:'Strong fit',initials:'MC'},
 {name:'Jordan Ellis',handle:'@jordaneats',category:'Food',followers:'96K',engagement:'8.2%',score:91,status:'Strong fit',initials:'JE'},
 {name:'Noah Rivera',handle:'@noahbuilds',category:'Technology',followers:'241K',engagement:'4.9%',score:88,status:'Review',initials:'NR'},
 {name:'Ava Morgan',handle:'@avamoves',category:'Fitness',followers:'74K',engagement:'7.4%',score:86,status:'Strong fit',initials:'AM'},
]
const nav = [['Overview',LayoutDashboard],['Discover',Search],['Creators',Users],['Relationships',HeartHandshake],['Campaigns',Megaphone],['Content',ClipboardCheck],['Calendar',CalendarDays],['Payments',WalletCards],['Analytics',TrendingUp],['Reports',Gauge]] as const

export default function Home(){
 const [active,setActive]=useState('Overview'); const [query,setQuery]=useState(''); const [showCreator,setShowCreator]=useState(false); const [toast,setToast]=useState('')
 const filtered=useMemo(()=>creators.filter(c=>`${c.name} ${c.handle} ${c.category}`.toLowerCase().includes(query.toLowerCase())),[query])
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2200)}
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><strong>ShineU</strong><span>Creator OS</span></div></div><div className="workspace"><div className="workspace-logo">N</div><div><b>Northstar</b><small>Growth team</small></div><ChevronDown size={15}/></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'nav-item active':'nav-item'} onClick={()=>{setActive(label);notify(`${label} workspace selected`)}}><Icon size={18}/><span>{label}</span>{label==='Campaigns'&&<em>4</em>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={()=>notify('Settings opened')}><Settings size={18}/><span>Settings</span></button><div className="user-card"><div className="avatar">GE</div><div><b>Gio Egre</b><small>Administrator</small></div><MoreHorizontal size={17}/></div></div></aside>
  <section className="content"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">S</div><b>ShineU</b></div><div className="crumb">Workspace <span>/</span> {active}</div><div className="top-actions"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search creators, campaigns…"/><kbd>⌘ K</kbd></label><button className="icon-btn" onClick={()=>notify('You are all caught up')}><Bell size={19}/><i/></button><button className="primary small" onClick={()=>setShowCreator(true)}><Plus size={16}/> Add creator</button></div></header>
   <div className="page"><div className="page-heading"><div><p className="eyebrow">Monday, September 14, 2026</p><h1>Good evening, Gio <span>✦</span></h1><p className="muted">Here’s what needs your attention across creator partnerships.</p></div><button className="ghost" onClick={()=>notify('Filters are ready to customize')}><Filter size={16}/> Filters</button></div>
    <div className="metric-grid"><Metric title="Campaign spend" value="$84,240" delta="12.8%" subtitle="vs. last month" icon={CircleDollarSign}/><Metric title="Attributed revenue" value="$312,680" delta="24.6%" subtitle="vs. last month" icon={TrendingUp}/><Metric title="Creator reach" value="4.82M" delta="18.2%" subtitle="vs. last month" icon={Users}/><Metric title="Avg. engagement" value="6.4%" delta="0.8%" subtitle="vs. last month" icon={Activity}/></div>
    <div className="main-grid"><section className="panel performance"><div className="panel-head"><div><h2>Campaign performance</h2><p>Revenue and spend over the last 30 days</p></div><button className="select">Last 30 days <ChevronDown size={14}/></button></div><div className="chart"><div className="chart-y"><span>$100k</span><span>$75k</span><span>$50k</span><span>$25k</span><span>$0</span></div><div className="chart-area"><div className="grid-lines"/><svg viewBox="0 0 760 240" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity=".18"/><stop offset="100%" stopOpacity="0"/></linearGradient></defs><path d="M0 205 C65 190 82 158 145 170 S220 120 280 138 S355 95 420 120 S500 70 555 92 S650 40 760 48 L760 240 L0 240Z" fill="url(#fill)"/><path d="M0 205 C65 190 82 158 145 170 S220 120 280 138 S355 95 420 120 S500 70 555 92 S650 40 760 48" fill="none" stroke="currentColor" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><div className="xlabels"><span>Aug 16</span><span>Aug 22</span><span>Aug 28</span><span>Sep 3</span><span>Sep 9</span><span>Sep 14</span></div></div></div><div className="legend"><span><i/> Revenue <b>$312.7K</b></span><span><i/> Spend <b>$84.2K</b></span><span className="roi"><Sparkles size={14}/> 3.71× ROAS</span></div></section>
     <section className="panel attention"><div className="panel-head"><div><h2>Needs attention</h2><p>Items that need a decision</p></div><button className="link" onClick={()=>notify('Opening all attention items')}>View all <ArrowUpRight size={15}/></button></div><Attention icon="content" title="4 content approvals" desc="Summer Creator Growth" action="Review" onClick={()=>notify('Opening content approvals')}/><Attention icon="deadline" title="2 deadlines tomorrow" desc="Tech Launch · 10:00 AM" action="Open" onClick={()=>notify('Opening tomorrow’s deadlines')}/><Attention icon="payment" title="3 payments pending" desc="$8,460 total" action="Review" onClick={()=>notify('Opening pending payments')}/></section></div>
    <section className="panel creators-panel"><div className="panel-head"><div><h2>Creator opportunities</h2><p>High-fit creators ready for your next partnership</p></div><button className="link" onClick={()=>{setActive('Discover');notify('Creator discovery opened')}}>Explore discovery <ArrowUpRight size={15}/></button></div><div className="creator-table"><div className="table-head"><span>Creator</span><span>Category</span><span>Audience</span><span>Engagement</span><span>Fit score</span><span/></div>{filtered.map(c=><div className="creator-row" key={c.handle}><div className="creator-name"><div className="avatar creator-avatar">{c.initials}</div><div><b>{c.name}</b><small>{c.handle}</small></div></div><span className="category">{c.category}</span><span>{c.followers}</span><span>{c.engagement}</span><span><strong className="score">{c.score}</strong> <small>{c.status}</small></span><button className="row-action" onClick={()=>notify(`Added ${c.name} to shortlist`)}>Shortlist</button></div>)}</div></section>
    <div className="bottom-grid"><section className="panel"><div className="panel-head"><div><h2>Active campaigns</h2><p>Current creator programs</p></div><button className="icon-btn subtle" onClick={()=>notify('Campaign menu opened')}><MoreHorizontal size={18}/></button></div><Campaign name="Summer Creator Growth" brand="Northstar" progress={78} creators="18 creators" revenue="$142K"/><Campaign name="Everyday Tech" brand="Shine Labs" progress={52} creators="11 creators" revenue="$86K"/><Campaign name="Weekend Wellness" brand="Northstar" progress={34} creators="9 creators" revenue="$44K"/></section><section className="panel"><div className="panel-head"><div><h2>Creator funnel</h2><p>This quarter</p></div><Target size={20}/></div><div className="funnel"><Funnel label="Discovered" value="1,284" width="100%"/><Funnel label="Contacted" value="642" width="74%"/><Funnel label="Interested" value="238" width="51%"/><Funnel label="Contracted" value="84" width="31%"/></div></section></div>
   </div></section>
  {showCreator&&<div className="modal-backdrop" onMouseDown={()=>setShowCreator(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Add creator</h2><p>Start a new creator relationship.</p></div><button className="icon-btn" onClick={()=>setShowCreator(false)}><X size={18}/></button></div><label>Creator name<input placeholder="e.g. Maya Chen"/></label><label>Social handle<input placeholder="@creator"/></label><label>Category<select><option>Beauty</option><option>Technology</option><option>Food</option><option>Fitness</option><option>Travel</option></select></label><button className="primary" onClick={()=>{setShowCreator(false);notify('Creator added to your CRM')}}>Add to creator CRM</button></div></div>}
  {toast&&<div className="toast"><ClipboardCheck size={16}/>{toast}</div>}
 </main>
}
function Metric({title,value,delta,subtitle,icon:Icon}:{title:string,value:string,delta:string,subtitle:string,icon:any}){return <div className="metric"><div className="metric-top"><span>{title}</span><div className="metric-icon"><Icon size={17}/></div></div><div className="metric-value">{value}</div><div className="metric-foot"><span className="up">↗ {delta}</span><small>{subtitle}</small></div></div>}
function Attention({icon,title,desc,action,onClick}:{icon:string,title:string,desc:string,action:string,onClick:()=>void}){return <div className="attention-row"><div className={`attention-icon ${icon}`}>{icon==='content'?<ClipboardCheck size={17}/>:icon==='deadline'?<CalendarDays size={17}/>:<WalletCards size={17}/>}</div><div><b>{title}</b><small>{desc}</small></div><button onClick={onClick}>{action}</button></div>}
function Campaign({name,brand,progress,creators,revenue}:{name:string,brand:string,progress:number,creators:string,revenue:string}){return <div className="campaign"><div className="campaign-icon">{name.slice(0,1)}</div><div className="campaign-main"><div><b>{name}</b><small>{brand} · {creators}</small></div><strong>{revenue}</strong><div className="progress"><span style={{width:`${progress}%`}}/></div></div><span className="progress-label">{progress}%</span></div>}
function Funnel({label,value,width}:{label:string,value:string,width:string}){return <div className="funnel-row"><span>{label}</span><div><i style={{width}}/></div><b>{value}</b></div>}
